### ISSUE TITLE
Fix broken API fetch

### ISSUE THREAD

**Issue by hugosandsjo** [hugosandsjo/OddityOasis#52]
Seems like the bored API is down. Fix the broken connection or change API

**Comment by vincyy24** [comment]
> Seems like the bored API is down. Fix the broken connection or change API

Can you suggest any other API to consider with the application in this case?
Like a random jokes API or random advice API (Advice Slip API)

**Comment by hugosandsjo** [comment]
I dont know any at the moment but feel free to choose something suitable!
