### ISSUE TITLE
Center main content in view

### ISSUE THREAD

**Issue by hugosandsjo** [hugosandsjo/OddityOasis#57]
Both on the y and x-axis

**Comment by msbalacse** [comment]
can i work on this issue. And I need a explain which UI part should i change.

**Comment by hugosandsjo** [comment]
Sure @msbalacse . I was thinking the section in App.jsx with the image and rendermaincontent needs to be centered in the viewport with consistent margin on the y and x-axis. How you want to solve it is up to you.
