### ISSUE TITLE
Make logo into a button that resets the app

### ISSUE THREAD

**Issue by hugosandsjo** [hugosandsjo/OddityOasis#63]

**Comment by codebymv** [comment]
I'll try and implement this

**Comment by hugosandsjo** [comment]
Please do! @codebymv

**Comment by hugosandsjo** [comment]
Or is it already fixed?

**Comment by codebymv** [comment]
I thought I added this with PR #64, were you looking for an actual button that has unique styles to be containing the logo or just the ability to reset the app state by clicking the header?

**Comment by hugosandsjo** [comment]
Nevermind, you fixed it! Thanks!
